### ISSUE TITLE
Landscape on iPhone the "we are" is getting tucked up under the nav bar.

### ISSUE THREAD

**Issue by br-gailitis** [heavycraft/heavycraft.io#1]

**Comment by br-gailitis** [comment]
This issue deals with using a full height hero (100vh).  We can add a few media queries to take care of this i think

**Comment by brocgailit** [comment]
This issue should be fixed in 3eddd91dddfd739ac9ad5e8890a18910b95be4fc

**Comment by br-gailitis** [comment]
This issue should be fixed in 3eddd91dddfd739ac9ad5e8890a18910b95be4fc
